// <auto-generated />
namespace DreamJob.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class member : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(member));
        
        string IMigrationMetadata.Id
        {
            get { return "201502232142493_member"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
