// <auto-generated />
namespace DreamJob.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class jobofferstatusesintoseparatetables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jobofferstatusesintoseparatetables));
        
        string IMigrationMetadata.Id
        {
            get { return "201502222056250_job-offer-statuses-into-separate-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
