// <auto-generated />
namespace DreamJob.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class contactdetailsonofferaccept : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contactdetailsonofferaccept));
        
        string IMigrationMetadata.Id
        {
            get { return "201502242226467_contact details on offer accept"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
