// <auto-generated />
namespace DreamJob.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class candidate_working_location : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(candidate_working_location));
        
        string IMigrationMetadata.Id
        {
            get { return "201505021129471_candidate_working_location"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
