//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeszcze wiele przed nami, mamy całkiem sporo pomysłów jak możemy poprawić i ulepszyć aplikację - mając na celu oba obozy: programistów i rekruterów.
        ///            System tworzymy po godzinach pracy, także nie zawsze jest czas i chęci. Jeśli będziemy widzieć, że czegoś bardzo potrzebujecie to dostarczymy takie rozwiązania. Jeśli coś nie będzie działać, lub będzie nie potrzebne czy bez sensu jesteśmy gotowi to zmieć i poprawić.
        ///            &lt;div&gt;Nasze pomysły i listę zadań można śledzić na trello: &lt;a target=&quot;_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_AboutDevelopers {
            get {
                return ResourceManager.GetString("About_AboutDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dream job - to portal dla programistów poszukujących pracy i dla rekruterów szukających pracowników.
        ///                Programistom umożliwiamy zachowanie pełnej anonimowości, tak długo jak będą tego chcieli.
        ///                Rekruterom oferujemy możliwość znalezienia idealnego kandydata..
        /// </summary>
        public static string About_AboutPortal {
            get {
                return ResourceManager.GetString("About_AboutPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programisto załóż konto, wypełnij swój profil oraz napisz, co potrafisz i czym chciałbyś się zajmować.
        ///            Ustaw swój profil jako aktywny i czekaj na oferty. To Ty decydujesz czy oferta jest dopasowana i pasuje do Twoich umiejętności.
        ///            Ty decydujesz kiedy i jakie dane osobowe przekazujesz rekruterowi..
        /// </summary>
        public static string About_WhyDeveloperShouldJoin {
            get {
                return ResourceManager.GetString("About_WhyDeveloperShouldJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekruterze załóż konto, uzupelnij swój profil i oznacz się jako aktywny. Uzyskasz dostęp do programistów chcących zmienić swoją pracę.
        ///            Możesz wyszukać intereującą Cię umiejętnośc programisty, przeczytać co chce robić i jeśli będzie on człowiekiem, którego potrzebujesz wysłać mu ofertę..
        /// </summary>
        public static string About_WhyRecruiterShouldJoin {
            get {
                return ResourceManager.GetString("About_WhyRecruiterShouldJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is required.
        /// </summary>
        public static string CommentAdd_Dto_TextIsRequired {
            get {
                return ResourceManager.GetString("CommentAdd_Dto_TextIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string ContactInformation_Dto_Email_Required {
            get {
                return ResourceManager.GetString("ContactInformation_Dto_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string ContactInformation_Dto_FirstName_Required {
            get {
                return ResourceManager.GetString("ContactInformation_Dto_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required.
        /// </summary>
        public static string ContactInformation_Dto_Phone_Required {
            get {
                return ResourceManager.GetString("ContactInformation_Dto_Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill level must be between {1} and {2}.
        /// </summary>
        public static string DeveloperSkill_Dto_Level_Range {
            get {
                return ResourceManager.GetString("DeveloperSkill_Dto_Level_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, thats embarasing. We promise we will fix that..
        /// </summary>
        public static string Error_GeneralErrorHeading {
            get {
                return ResourceManager.GetString("Error_GeneralErrorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask google.
        /// </summary>
        public static string Error_NotFoundAskGoogle {
            get {
                return ResourceManager.GetString("Error_NotFoundAskGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We dont have it. You have two options.
        /// </summary>
        public static string Error_NotFoundHeading {
            get {
                return ResourceManager.GetString("Error_NotFoundHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is new beginning.
        /// </summary>
        public static string Error_StartFromBegining {
            get {
                return ResourceManager.GetString("Error_StartFromBegining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page always works.
        /// </summary>
        public static string Error_ThisPageAlwaysWorks {
            get {
                return ResourceManager.GetString("Error_ThisPageAlwaysWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Home_Experience {
            get {
                return ResourceManager.GetString("Home_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Home_Position {
            get {
                return ResourceManager.GetString("Home_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Home_Salary {
            get {
                return ResourceManager.GetString("Home_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Home_Skills {
            get {
                return ResourceManager.GetString("Home_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Home_Summary {
            get {
                return ResourceManager.GetString("Home_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string JobOffer_Accept {
            get {
                return ResourceManager.GetString("JobOffer_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string JobOffer_AddComment {
            get {
                return ResourceManager.GetString("JobOffer_AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to offers.
        /// </summary>
        public static string JobOffer_BackToOffer {
            get {
                return ResourceManager.GetString("JobOffer_BackToOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string JobOffer_Cancel {
            get {
                return ResourceManager.GetString("JobOffer_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string JobOffer_Confirm {
            get {
                return ResourceManager.GetString("JobOffer_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string JobOffer_Reject {
            get {
                return ResourceManager.GetString("JobOffer_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string JobOffer_Send {
            get {
                return ResourceManager.GetString("JobOffer_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status history.
        /// </summary>
        public static string JobOffer_StatusHistory {
            get {
                return ResourceManager.GetString("JobOffer_StatusHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string JobOffer_Submit {
            get {
                return ResourceManager.GetString("JobOffer_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (view profile).
        /// </summary>
        public static string JobOffer_ViewProfile {
            get {
                return ResourceManager.GetString("JobOffer_ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job offer company name must be at least {2} characters long.
        /// </summary>
        public static string JobOfferSend_Dto_CompanyName_Length {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_CompanyName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job offer company name is required..
        /// </summary>
        public static string JobOfferSend_Dto_CompanyName_Required {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_CompanyName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Id is required.
        /// </summary>
        public static string JobOfferSend_Dto_DeveloperId_Required {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_DeveloperId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job offer text must be at least {2} characters long.
        /// </summary>
        public static string JobOfferSend_Dto_JobOfferText_Length {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_JobOfferText_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job offer text is required..
        /// </summary>
        public static string JobOfferSend_Dto_JobOfferText_Required {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_JobOfferText_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that the offer you are sending matches candidate requirements..
        /// </summary>
        public static string JobOfferSend_Dto_OfferMatchesProfile {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_OfferMatchesProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job offer position must be at least {2} characters long.
        /// </summary>
        public static string JobOfferSend_Dto_Position_Length {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_Position_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job offer position is required..
        /// </summary>
        public static string JobOfferSend_Dto_Position_Required {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_Position_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you have read candidate profile before you sends the offer to him..
        /// </summary>
        public static string JobOfferSend_Dto_ProfileWasReadBeforeSending {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_ProfileWasReadBeforeSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job offer requirements must be at least {2} characters long.
        /// </summary>
        public static string JobOfferSend_Dto_Requirements_Length {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_Requirements_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job offer requirements are required..
        /// </summary>
        public static string JobOfferSend_Dto_Requirements_Required {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_Requirements_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job offer salary is required.
        /// </summary>
        public static string JobOfferSend_Dto_Salary_Required {
            get {
                return ResourceManager.GetString("JobOfferSend_Dto_Salary_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Layout_About {
            get {
                return ResourceManager.GetString("Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Layout_Login {
            get {
                return ResourceManager.GetString("Layout_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Layout_Logout {
            get {
                return ResourceManager.GetString("Layout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Layout_Me {
            get {
                return ResourceManager.GetString("Layout_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Layout_Register {
            get {
                return ResourceManager.GetString("Layout_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Layout_Search {
            get {
                return ResourceManager.GetString("Layout_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Menu_NewMessages {
            get {
                return ResourceManager.GetString("Menu_NewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to profile.
        /// </summary>
        public static string Profile_BackToProfile {
            get {
                return ResourceManager.GetString("Profile_BackToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Profile_Edit {
            get {
                return ResourceManager.GetString("Profile_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to profile edit.
        /// </summary>
        public static string Profile_GoToProfileEdit {
            get {
                return ResourceManager.GetString("Profile_GoToProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is here.
        /// </summary>
        public static string Profile_GoToPublicProfile {
            get {
                return ResourceManager.GetString("Profile_GoToPublicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Profile_Login {
            get {
                return ResourceManager.GetString("Profile_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login now.
        /// </summary>
        public static string Profile_LoginNow {
            get {
                return ResourceManager.GetString("Profile_LoginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, you made it. Great!.
        /// </summary>
        public static string Profile_LoginSuccessHeader {
            get {
                return ResourceManager.GetString("Profile_LoginSuccessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New skill level.
        /// </summary>
        public static string Profile_NewSkillLevel {
            get {
                return ResourceManager.GetString("Profile_NewSkillLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New skill name.
        /// </summary>
        public static string Profile_NewSkillName {
            get {
                return ResourceManager.GetString("Profile_NewSkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your&apos;s profile in not active, change that in order to send job offers to best developers like one.
        /// </summary>
        public static string Profile_RecruiterProfileIsNotActiveWarning {
            get {
                return ResourceManager.GetString("Profile_RecruiterProfileIsNotActiveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Profile_Register {
            get {
                return ResourceManager.GetString("Profile_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to fully use our application please update your profile and set it as active.&lt;br/&gt;Profiles that are not set as active cannot send any offers and are invisible when searching..
        /// </summary>
        public static string Profile_RegisterActivationInformation {
            get {
                return ResourceManager.GetString("Profile_RegisterActivationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find a dream job.
        /// </summary>
        public static string Profile_RegisterAsDeveloper {
            get {
                return ResourceManager.GetString("Profile_RegisterAsDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find a dream worker.
        /// </summary>
        public static string Profile_RegisterAsRecruiter {
            get {
                return ResourceManager.GetString("Profile_RegisterAsRecruiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register and.
        /// </summary>
        public static string Profile_RegisterHeader {
            get {
                return ResourceManager.GetString("Profile_RegisterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you can now login to the system..
        /// </summary>
        public static string Profile_RegisterSuccessHeader {
            get {
                return ResourceManager.GetString("Profile_RegisterSuccessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Profile_RemoveSkillButtonText {
            get {
                return ResourceManager.GetString("Profile_RemoveSkillButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pln monthly netto.
        /// </summary>
        public static string Profile_Salary {
            get {
                return ResourceManager.GetString("Profile_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send job offer.
        /// </summary>
        public static string Profile_SendJobOffer {
            get {
                return ResourceManager.GetString("Profile_SendJobOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills:.
        /// </summary>
        public static string Profile_Skills {
            get {
                return ResourceManager.GetString("Profile_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Profile_Update {
            get {
                return ResourceManager.GetString("Profile_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Profile_Warning {
            get {
                return ResourceManager.GetString("Profile_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string ProfileLogin_Dto_EmailRequired {
            get {
                return ResourceManager.GetString("ProfileLogin_Dto_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string ProfileLogin_Dto_PasswordRequired {
            get {
                return ResourceManager.GetString("ProfileLogin_Dto_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me section is required.
        /// </summary>
        public static string ProfilePrivateDeveloperEdit_Dto_AboutMe_Required {
            get {
                return ResourceManager.GetString("ProfilePrivateDeveloperEdit_Dto_AboutMe_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current working location is required.
        /// </summary>
        public static string ProfilePrivateDeveloperEdit_Dto_CurrentWorkingLocation_Required {
            get {
                return ResourceManager.GetString("ProfilePrivateDeveloperEdit_Dto_CurrentWorkingLocation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name is required.
        /// </summary>
        public static string ProfilePrivateDeveloperEdit_Dto_DisplayName_Required {
            get {
                return ResourceManager.GetString("ProfilePrivateDeveloperEdit_Dto_DisplayName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience should be in range between {1} and {2}.
        /// </summary>
        public static string ProfilePrivateDeveloperEdit_Dto_Experience_Range {
            get {
                return ResourceManager.GetString("ProfilePrivateDeveloperEdit_Dto_Experience_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience field is required.
        /// </summary>
        public static string ProfilePrivateDeveloperEdit_Dto_Experience_Required {
            get {
                return ResourceManager.GetString("ProfilePrivateDeveloperEdit_Dto_Experience_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for section is required.
        /// </summary>
        public static string ProfilePrivateDeveloperEdit_Dto_LookingFor_Required {
            get {
                return ResourceManager.GetString("ProfilePrivateDeveloperEdit_Dto_LookingFor_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary should be in range between {1} and {2}.
        /// </summary>
        public static string ProfilePrivateDeveloperEdit_Dto_Salary_Range {
            get {
                return ResourceManager.GetString("ProfilePrivateDeveloperEdit_Dto_Salary_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary information is required.
        /// </summary>
        public static string ProfilePrivateDeveloperEdit_Dto_Salary_Required {
            get {
                return ResourceManager.GetString("ProfilePrivateDeveloperEdit_Dto_Salary_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiter email is required.
        /// </summary>
        public static string ProfilePrivateRecruiter_Dto_Email_Required {
            get {
                return ResourceManager.GetString("ProfilePrivateRecruiter_Dto_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiter employer name is required.
        /// </summary>
        public static string ProfilePrivateRecruiter_Dto_Employer_Required {
            get {
                return ResourceManager.GetString("ProfilePrivateRecruiter_Dto_Employer_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiter first name is required.
        /// </summary>
        public static string ProfilePrivateRecruiter_Dto_FirstName_Required {
            get {
                return ResourceManager.GetString("ProfilePrivateRecruiter_Dto_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiter last name is required.
        /// </summary>
        public static string ProfilePrivateRecruiter_Dto_LastName_Required {
            get {
                return ResourceManager.GetString("ProfilePrivateRecruiter_Dto_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string ProfileRegisterDto_Email_Required {
            get {
                return ResourceManager.GetString("ProfileRegisterDto_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {2} characters long.
        /// </summary>
        public static string ProfileRegisterDto_Password_Length {
            get {
                return ResourceManager.GetString("ProfileRegisterDto_Password_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string ProfileRegisterDto_Password_Required {
            get {
                return ResourceManager.GetString("ProfileRegisterDto_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiting to:.
        /// </summary>
        public static string RecruitingToText {
            get {
                return ResourceManager.GetString("RecruitingToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers with salary in range:.
        /// </summary>
        public static string Search_DevelopersWithSalaryInRange {
            get {
                return ResourceManager.GetString("Search_DevelopersWithSalaryInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter skill name below. You can use &apos;,&apos; or &apos;;&apos; or space to enter multiple skills.
        /// </summary>
        public static string Search_EnterSearchSkillHereSeparateByCommandOrSemicolon {
            get {
                return ResourceManager.GetString("Search_EnterSearchSkillHereSeparateByCommandOrSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching skills:.
        /// </summary>
        public static string Search_MatchingSkills {
            get {
                return ResourceManager.GetString("Search_MatchingSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum salary:.
        /// </summary>
        public static string Search_MaximumSalary {
            get {
                return ResourceManager.GetString("Search_MaximumSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minumum salary:.
        /// </summary>
        public static string Search_MinumumSalary {
            get {
                return ResourceManager.GetString("Search_MinumumSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested skills:.
        /// </summary>
        public static string Search_RequestedSkills {
            get {
                return ResourceManager.GetString("Search_RequestedSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by salary.
        /// </summary>
        public static string Search_SearchBySalary {
            get {
                return ResourceManager.GetString("Search_SearchBySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by skill.
        /// </summary>
        public static string Search_SearchBySkill {
            get {
                return ResourceManager.GetString("Search_SearchBySkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are stars:.
        /// </summary>
        public static string Search_SearchResults {
            get {
                return ResourceManager.GetString("Search_SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the maximum salary.
        /// </summary>
        public static string SearchSalary_Dto_Maximum_Required {
            get {
                return ResourceManager.GetString("SearchSalary_Dto_Maximum_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the minimum salary.
        /// </summary>
        public static string SearchSalary_Dto_Minimum_Required {
            get {
                return ResourceManager.GetString("SearchSalary_Dto_Minimum_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search skill name is required to do the search.
        /// </summary>
        public static string SearchSkill_Dto_Skill_Required {
            get {
                return ResourceManager.GetString("SearchSkill_Dto_Skill_Required", resourceCulture);
            }
        }
    }
}
