// <auto-generated />
namespace DreamJob.Database.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class removedId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedId));
        
        string IMigrationMetadata.Id
        {
            get { return "201408311136463_removedId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
