// <auto-generated />
namespace DreamJob.Database.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class developer_isLookingForJob : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(developer_isLookingForJob));
        
        string IMigrationMetadata.Id
        {
            get { return "201410041858258_developer_isLookingForJob"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
