// <auto-generated />
namespace DreamJob.Database.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class base_entity_uses_datetime2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(base_entity_uses_datetime2));
        
        string IMigrationMetadata.Id
        {
            get { return "201410022153091_base_entity_uses_datetime2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
